dist: trusty
language: csharp
mono: none
dotnet: 2.0.0-preview2-006497
dist: trusty

before_script:
  - dotnet restore

script:
  - dotnet test

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack src -c Release && dotnet nuget push src/bin/Release/Shell.NET.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master
