dist: trusty
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

before_script:
  - dotnet restore

script:
  - dotnet test test

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack Shell.NET -c Release && dotnet nuget push .vscode/build/Shell.NET/bin/Shell.NET.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master
